# Generated by Django 5.2.16 on 2026-07-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='system_prompt',
            field=models.TextField(blank=True, default="You are a sales and support AI assistant for a business. Your goals: 1) QUALIFY leads by asking about their needs and budget, 2) PROVIDE accurate information from the knowledge base, 3) CONVERT conversations into sales by highlighting benefits and handling objections, 4) ESCALATE to human agent when the customer asks to speak to a person. Always be professional, friendly, and persuasive. Use the knowledge base to answer accurately. If you don't know something, be honest and offer to connect with a human agent."),
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('file', models.FileField(upload_to='knowledge_docs/%Y/%m/')),
                ('category', models.CharField(choices=[('general', 'General'), ('products', 'Products'), ('services', 'Services'), ('pricing', 'Pricing'), ('faq', 'FAQ'), ('policies', 'Policies'), ('hours', 'Business Hours'), ('contact', 'Contact Info'), ('other', 'Other')], default='general', max_length=50)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ai_agent.aiagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
