# Generated by Django 5.2.16 on 2026-07-29 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_alter_aiagent_system_prompt_knowledgedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo/Instrução')),
                ('priority', models.IntegerField(default=0, help_text='Maior número = maior prioridade no prompt')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_rules', to='ai_agent.aiagent')),
            ],
            options={
                'verbose_name': 'Regra do Negócio',
                'verbose_name_plural': 'Regras do Negócio',
                'ordering': ['-priority', 'title'],
            },
        ),
    ]
