server {
    listen 80;
    server_name crm.ivro.com.br;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name crm.ivro.com.br;

    ssl_certificate /etc/letsencrypt/live/crm.ivro.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/crm.ivro.com.br/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 20M;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /var/www/crm/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /var/www/crm/media/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    proxy_headers_hash_max_size 1024;
    proxy_headers_hash_bucket_size 128;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/var/www/crm/run/crm.sock;
        proxy_read_timeout 120s;
    }
}
